// https://tickets.rolandgarros.com/api/v2/ticket/cart/ticket-product-by-seat

const book_response = {
    "tickets": [
        {
            "court": "PC",
            "category": "Cat. GOLD",
            "isFreeSeating": false,
            "price": 985.0,
            "cartProductId": 127397407,
            "stairs": "22",
            "row": "8",
            "chairId": 10997486,
            "access": "C20",
            "seatNumber": 51,
            "showLodge": false,
            "lodge": "5",
            "standId": 66,
            "zoneId": 572,
            "bobId": "85851",
            "ticketId": 19374825,
            "sessionType": "SOI",
            "isNotYetPlaced": false,
            "offerFamilyTypeTitle": "Premium Privilège",
            "offerFamilyTypeCode": "prem_privilege",
            "insurance": null,
            "upgradeProduct": null,
            "day": "Thursday 29 May",
            "days": "Thursday 29 May",
            "ticketSessionDay": "2025-05-29",
            "productSessionDays": "2025-05-29",
            "isPanoramaViewAvailable": true,
            "sessionTypes": "SOI",
            "categoryCode": "Cat. OR",
            "productPrice": 985.0,
            "showOnlyAccessAndStairs": false
        },
        {
            "court": "PC",
            "category": "Cat. GOLD",
            "isFreeSeating": false,
            "price": 985.0,
            "cartProductId": 127397408,
            "stairs": "22",
            "row": "8",
            "chairId": 10997485,
            "access": "C20",
            "seatNumber": 50,
            "showLodge": false,
            "lodge": "5",
            "standId": 66,
            "zoneId": 572,
            "bobId": "85851",
            "ticketId": 19374826,
            "sessionType": "SOI",
            "isNotYetPlaced": false,
            "offerFamilyTypeTitle": "Premium Privilège",
            "offerFamilyTypeCode": "prem_privilege",
            "insurance": null,
            "upgradeProduct": null,
            "day": "Thursday 29 May",
            "days": "Thursday 29 May",
            "ticketSessionDay": "2025-05-29",
            "productSessionDays": "2025-05-29",
            "isPanoramaViewAvailable": true,
            "sessionTypes": "SOI",
            "categoryCode": "Cat. OR",
            "productPrice": 985.0,
            "showOnlyAccessAndStairs": false
        }
    ],
    "managementFees": 4,
    "productsWithoutInsuranceCount": 2,
    "additionalProducts": [],
    "upgradeProducts": [],
    "nbProductsToShow": 2
}